import time
import pyttsx3

engine = pyttsx3.init()
voices = engine.getProperty('voices')
"""
print(voices)
print(voices[1].id)
print(voices[2].id)
print(voices[3].id)
print(voices[4].id)
print(voices[5].id)
print(voices[6].id)
print(voices[7].id)
print(voices[8].id)
print(voices[9].id)
print(voices[10].id)
print(voices[11].id)
print(voices[12].id)
print(voices[12].id)
print(voices[13].id)
print(voices[14].id)
print(voices[15].id)
print(voices[16].id)
print(voices[17].id)
print(voices[18].id)
print(voices[19].id)
print(voices[20].id)
print(voices[21].id)
print(voices[22].id)
print(voices[23].id)
print(voices[24].id)
print(voices[25].id)
print(voices[26].id)
print(voices[27].id)
print(voices[28].id)
print(voices[29].id)
print(voices[30].id)
print(voices[31].id)
print(voices[32].id)
print(voices[33].id)
print(voices[34].id)
print(voices[35].id)
print(voices[36].id)
print(voices[37].id)
print(voices[38].id)
print(voices[39].id)
print(voices[40].id)
print(voices[41].id)
print(voices[42].id)
print(voices[43].id)
print(voices[44].id)
print(voices[45].id)
print(voices[46].id)
print(voices[47].id)
"""
#7 32 33
engine.setProperty('voice', voices[33].id)
rate = engine.getProperty('rate')
engine.setProperty('rate', rate+10)
engine.say('hello')
time.sleep(2)
'''
from playsound import playsound
playsound('BTS.wav')

engine.say('Welcome to Lucia Vision')
engine.say('This is an Advance automated Artificial Intelligence')
'''
'''
time.sleep(2)
engine.say('Welcome to Lucia Vision')
time.sleep(2)
engine.say("How can i help you?")'''
engine.runAndWait()